# Generated by Django 3.2.3 on 2021-05-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('tlf', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('PVP', models.FloatField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('TotalVenta', models.FloatField(max_length=9)),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='LineasVenta',
            fields=[
                ('idLineaVenta', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(max_length=5)),
                ('PrecioPorLinea', models.FloatField(max_length=9)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.producto')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.cliente')),
            ],
        ),
    ]
