# Generated by Django 3.2.3 on 2021-05-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='TotalVenta',
            field=models.FloatField(blank=True, max_length=9, null=True),
        ),
    ]
