# Generated by Django 3.2.3 on 2021-05-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormsApp', '0003_alter_lineasventa_idventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineasventa',
            name='PrecioPorLinea',
        ),
    ]
