# Generated by Django 3.2.3 on 2021-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsApp', '0004_remove_lineasventa_precioporlinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineasventa',
            name='PrecioPorLinea',
            field=models.FloatField(blank=True, max_length=9, null=True),
        ),
    ]
